version: '3.8'

services:
  app:
    image: excel-export
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/test_db
    volumes:
      - ./output:/usr/local/bin/output
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: